### ISSUE TITLE
[Suggestion] Support for 2FA

### ISSUE THREAD

**Issue by ben-nsng** [alebeck/boring#10]
Hi,

I found this tool really helpful for managing SSH tunnels. However, since my servers are protected by 2FA, it's great that this tool also supports 2FA input.

This issue is a suggestion or idea for supporting 2FA input. When the server is protected by 2FA and using Boring to tunnel to the server, the following error message is displayed.

`[19:12:07] ERROR Tunnel tunnel could not be opened: could not setup SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`

The expected behavior is that when SSH is authenticated, the SSH server sends back "Authentications that can continue: keyboard-interactive," indicating that second-factor authentication is required. The terminal should prompt the user to enter the 2FA code to continue the authentication.

`(user@IP) Verification code: `

**Comment by alebeck** [comment]
Hi, nice idea! The only problem I see is that, in the 2FA case, automatic re-connections wouldn't work anymore. So one of the major selling points of any ssh tunnel manager disappears. For that reason, this kind of interactive usage wasn't really in my focus until now. What value does the app still provide to you if there is no transparent re-connections in the background? Just tunnel management? Keepalives?
