### ISSUE TITLE
RFC systemd support

### ISSUE THREAD

**Issue by richard-hajek** [alebeck/boring#13]
## Elevator pitch

I propose a change to adopt partial systemd support. Because all deamons should be living under one roof. 

## Reasoning

I think systemd support could be beneficial. For me the biggest advantage would be finding the daemon easily during debugging and fine tuning. To be blunt, it would be much easier to do `journalctl -u boringd` then to hunt down where does boring store logs. However I understand that systemd is a contentious topic, so

## Backwards compatibility

- If there is no systemd on the system, the current behavior would stay
- If there is systemd, but no boringd service unit on the system, the current behavior would stay
- In case there is systemd and a boringd service (regardless of if it is running), try to connect

## Drawbacks

This however is a bit of an anti-pattern - the behavior of boring would change if systemd was installed or removed, which is likely what the user wouldn't expect. But I must believe that it is not a usual situation for a distro to switch init systems.

Additionally, checking for presence of systemd and boringd service unit would incur more slowdown, more points of failure, most likely pulling more libraries and thus more complexity.

Or just do it safely and disable systemd support by default always regardless of the environment, and have the support enabled conditionally in the config.

## Needed changes

Changes in the code base would include preventing `daemon` from forking, and making it log out to stdout. I would be willing to implement the changes if you believe they would be beneficial.

I can also take care of writing the systemd unit and shipping it on AUR. I do not have experience with other distros though

**Comment by aivanise** [comment]
I second this, it does not have to be that complicated though, the --nofork flag and a sample unit file should be enough for start.

**Comment by alebeck** [comment]
Hi, thanks for the suggestion! Currently I don't see the few benefits of using systemd outweigh the added complexity TBH. Most problematic in my opinion is that systemd is not available on macOS, Windows, and even some Linux systems, and I don't want to diverge too much between the target platforms nor add that kind of maintenance overhead. Furthermore, this would require installation logic (for creating the unit file), while currently it's sufficient to just download the binary and get going :)

I think that a simple and lightweight program -- that doesn't need the full lifecycle management of systemd -- can manage its daemon itself; systemd is not a must. 

That said, logging would probably benefit from it. But even here, why not just `tail -f $TMPDIR/boringd.log` to follow logs during debugging, or redirect logs to your desired location via the designated environment variable `$BORING_LOG_FILE`?

**Comment by richard-hajek** [comment]
Fair enough!

**Comment by richard-hajek** [comment]
@aivanise 

If you are inerested, you can use this to monitor boring by systemd

```
[Unit]
Description=Boring SSH tunnel service

[Service]
Type=simple
Environment=DEBUG=1
Environment=BORING_LOG_FILE=/tmp/.boringd
ExecStart=bash -c "/usr/bin/boring --daemon & /usr/bin/tail -F /tmp/.boringd | systemd-cat -t boring"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
