### ISSUE TITLE
Use XDG_CONFIG_HOME dir to store app config

### ISSUE THREAD

**Issue by frabarz** [alebeck/boring#3]
I wanted to suggest a small improvement to how boring stores its configuration. It currently saves the config file in `$HOME/.boring.toml`, but it would be better if it could follow the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/) instead. This way the config would go into `$XDG_CONFIG_HOME/boring/`, which defaults to `~/.config/boring/`.

It's cleaner since it avoids cluttering the home directory with dotfiles and helps keep everything organized. Plus, it's a standard a lot of apps are moving toward, making things more consistent for users who care about keeping their home directory tidy. Should be a simple change, but it would really enhance the user experience.

**Comment by alebeck** [comment]
Done.
