### ISSUE TITLE
[Suggestion] Support for LocalForward coming from SSH config

### ISSUE THREAD

**Issue by jygastaud** [alebeck/boring#6]
In the SSH config, you could declare multiple `LocalForward`.

```
Host forward.XXXX
  Hostname XXXX
  User XXXX
  LocalForward 9443 XXXX:443
  LocalForward 9444 XXX:443
```

Boring comes as a replacement of that but you need to manage each forward individually  (or by group if #5 is implemented).

However If boring could detect and convert / interpret the already existing rules, it could a real win, just for the mechanisms of listing and reconnexion.

**Comment by alebeck** [comment]
Hi, not planning to implement that at the moment. I like that tunnels are configured from a single entry point currently (`~/.boring.toml`), and I feel that sourcing tunnel definitions from multiple configurations might make things less transparent. However, I can reconsider if I come across more good arguments for this!
