### ISSUE TITLE
Unclear error (illegal base64 data at input byte 4) when trying to open tunnel

### ISSUE THREAD

**Issue by cdfuller** [alebeck/boring#8]
```
ERROR Tunnel fic-prod could not be opened: could not make run config: could not make client config: knownhosts: /Users/codyfuller/.ssh/known_hosts:20: illegal base64 data at input byte 4
```

### .boring.toml
```
[[tunnels]]
name = "fic-prod"
local = "5234"
remote = "localhost:5432"
host = "willis-tower"
```

### .ssh/config
```
Host willis-tower
    HostName 107.X.X.X
    User cody
    ForwardAgent yes
```

Manually calling the tunnel using `ssh -L 5234:localhost:5432 willis-tower` works fine.

version 0.4.1 on macOS Sonoma 14.5 M1 Pro using the arm64 build. Let me know if there's any other info I can provide.

**Comment by alebeck** [comment]
It looks like the host key callback can not be created from your ~/.ssh/known_hosts file. This error actually originates from within golang.org/x/crypto/ssh/knownhosts. Can you inspect that file (specifically line 20) for any invalid base64 characters/other corruptions? If that specific host is not needed, can you remove it? It could be that golang's knownhosts package implements stricter validation than ssh...
